

ginWhiskeyTeaTable = {(1, 1, 1): "Whiskey Sour",
					(1, 1, 0): "Old Fashion",
					(1, 1, -1): "Whiskey Coke", 
					(1, 0, 1): "Pickle Back",
					(1, 0, 0): "Tequila Sunrise", 
					(1, 0, -1): "Margarita", 
					(1, -1, 1): "Freddy Fudpucker", 
					(1, -1, 0): "Bacardi Cocktail", 
					(1, -1, 1): "Rum and Coke",
					(1, -1, 0): "Mojito",
					(1, -1, -1): "Daiquiri",
					(0, 1, 1): "Malibu",
					(0, 1, 0): "Blue Hawaii",
					(0, 1, -1): "Mai Tai",
					(0, 0, 1): "Gimlet",
					(0, 0, 0): "Gin and Tonic",
					(0, 0, -1): "French 75",
					(0, -1, 1): "White Russian",
					(0, -1, 0): "Cranberry Vodka",
					(0, -1, -1): "Appletini",
					(-1, 1, 1): "Cosmo",
					(-1, 1, 0): "Blue Guy",
					(-1, 1, -1): "Screwdriver",
					(-1, 0 , 1): "Moscow Mule", 
					(-1, 0, 0): "Lemon Drop",
					(-1, 0, -1): "Sex on the Beach",
					(-1, -1, 1): "Mimosa",
					(-1, -1, 0): "Long Island",
					(-1, -1, -1): "SF Slide"
					}