CREATE TABLE main.DRINKNAMES(
    ID    TEXT    KEY,
    GENDER    TEXT,
    COLLEGE TEXT,
    Whiskey_Sour    INT,
    Old_Fashion    INT,
    Whiskey_Coke    INT,
    Pickle_Back    INT,
    Tequila_Sunrise    INT,
    Margarita    INT,
    FreddyåÊFudpucker    INT,
    Bacardi_Cocktail    INT,
    Rum_and_Coke    INT,
    Mojito    INT,
    Daiquiri    INT,
    Malibu    INT,
    Blue_Hawaii    INT,
    Mai_Tai    INT,
    Gimlet    INT,
    Gin_and_Tonic    INT,
    French_75    INT,
    White Russian    INT,
    Cran_Vodka    INT,
    Appletini    INT,
    Cosmo    INT,
    Blue_Guy    INT,
    Screwdriver    INT,
    Moscow_Mule    INT,
    Lemon_Drop    INT,
    Sex_on_the_Beach    INT,
    Mimosa    INT,
    Long_Island    INT,
    SF_Slide    INT,
    suggestions    TEXT,
    startDate    DATE,
    submitDate    DATE,
    netid    TEXT
);